library(pheatmap)
load("第二问数据处理.RData")
dailyToMonthly <- function(daily_data, fn = function(x) rowMeans(x, na.rm = TRUE)) {
    monthly_data <- cbind(fn(daily_data[, 1:31]), fn(daily_data[, 32:60]), fn(daily_data[, 61:91]), fn(daily_data[, 92:121]), fn(daily_data[, 122:152]), fn(daily_data[, 153:182]), fn(daily_data[, 183:213]), fn(daily_data[, 214:244]), fn(daily_data[, 245:274]), fn(daily_data[, 275:305]), fn(daily_data[, 306:335]), fn(daily_data[, 336:366]))
    colnames(monthly_data) <- c("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")
    return(monthly_data)
}
superior_basin_min_air_temperature <- dailyToMonthly(superior_basin_daliy[[1]])
superior_basin_max_air_temperature <- dailyToMonthly(superior_basin_daliy[[2]])
superior_basin_mean_precipitation <- dailyToMonthly(superior_basin_daliy[[3]], function(x) rowSums(x, na.rm = TRUE))
superior_basin_mean_air_temperature <- dailyToMonthly(superior_basin_daliy[[4]])
superior_basin_mean_dewpoint <- dailyToMonthly(superior_basin_daliy[[5]])
superior_basin_mean_wind_speed <- dailyToMonthly(superior_basin_daliy[[6]])
superior_basin_mean_cloud_cover <- dailyToMonthly(superior_basin_daliy[[7]])
superior_mean_surface_water_temperature <- dailyToMonthly(superior_mean_surface_water_temperature)
michigan_basin_min_air_temperature <- dailyToMonthly(michigan_basin_daliy[[1]])
michigan_basin_max_air_temperature <- dailyToMonthly(michigan_basin_daliy[[2]])
michigan_basin_mean_precipitation <- dailyToMonthly(michigan_basin_daliy[[3]], function(x) rowSums(x, na.rm = TRUE))
michigan_basin_mean_air_temperature <- dailyToMonthly(michigan_basin_daliy[[4]])
michigan_basin_mean_dewpoint <- dailyToMonthly(michigan_basin_daliy[[5]])
michigan_basin_mean_wind_speed <- dailyToMonthly(michigan_basin_daliy[[6]])
michigan_basin_mean_cloud_cover <- dailyToMonthly(michigan_basin_daliy[[7]])
michigan_mean_surface_water_temperature <- dailyToMonthly(michigan_huron_mean_surface_water_temperature)
huron_basin_min_air_temperature <- dailyToMonthly(huron_basin_daliy[[1]])
huron_basin_max_air_temperature <- dailyToMonthly(huron_basin_daliy[[2]])
huron_basin_mean_precipitation <- dailyToMonthly(huron_basin_daliy[[3]], function(x) rowSums(x, na.rm = TRUE))
huron_basin_mean_air_temperature <- dailyToMonthly(huron_basin_daliy[[4]])
huron_basin_mean_dewpoint <- dailyToMonthly(huron_basin_daliy[[5]])
huron_basin_mean_wind_speed <- dailyToMonthly(huron_basin_daliy[[6]])
huron_basin_mean_cloud_cover <- dailyToMonthly(huron_basin_daliy[[7]])
huron_mean_surface_water_temperature <- dailyToMonthly(michigan_huron_mean_surface_water_temperature)
erie_basin_min_air_temperature <- dailyToMonthly(erie_basin_daliy[[1]])
erie_basin_max_air_temperature <- dailyToMonthly(erie_basin_daliy[[2]])
erie_basin_mean_precipitation <- dailyToMonthly(erie_basin_daliy[[3]], function(x) rowSums(x, na.rm = TRUE))
erie_basin_mean_air_temperature <- dailyToMonthly(erie_basin_daliy[[4]])
erie_basin_mean_dewpoint <- dailyToMonthly(erie_basin_daliy[[5]])
erie_basin_mean_wind_speed <- dailyToMonthly(erie_basin_daliy[[6]])
erie_basin_mean_cloud_cover <- dailyToMonthly(erie_basin_daliy[[7]])
erie_mean_surface_water_temperature <- dailyToMonthly(erie_mean_surface_water_temperature)
ontario_basin_min_air_temperature <- dailyToMonthly(ontario_basin_daliy[[1]])
ontario_basin_max_air_temperature <- dailyToMonthly(ontario_basin_daliy[[2]])
ontario_basin_mean_precipitation <- dailyToMonthly(ontario_basin_daliy[[3]], function(x) rowSums(x, na.rm = TRUE))
ontario_basin_mean_air_temperature <- dailyToMonthly(ontario_basin_daliy[[4]])
ontario_basin_mean_dewpoint <- dailyToMonthly(ontario_basin_daliy[[5]])
ontario_basin_mean_wind_speed <- dailyToMonthly(ontario_basin_daliy[[6]])
ontario_basin_mean_cloud_cover <- dailyToMonthly(ontario_basin_daliy[[7]])
ontario_mean_surface_water_temperature <- dailyToMonthly(ontario_mean_surface_water_temperature)
matrixToRow <- function(matrix_data) {
    return(unlist(as.data.frame(t(matrix_data[as.character(2000:2020), ]))))
}
superior_cor <- cbind(matrixToRow(superior_basin_min_air_temperature), matrixToRow(superior_basin_max_air_temperature), matrixToRow(superior_basin_mean_precipitation), matrixToRow(superior_basin_mean_air_temperature), matrixToRow(superior_basin_mean_dewpoint), matrixToRow(superior_basin_mean_wind_speed), matrixToRow(superior_basin_mean_cloud_cover), matrixToRow(superior_mean_surface_water_temperature), matrixToRow(superior_mean_evaporation), matrixToRow(superior_mean_run_off), matrixToRow(superior_mean_water_level))
colnames(superior_cor) <- c("低温", "高温", "降水", "均温", "露点", "风速", "云盖", "水温", "蒸发", "径流", "水位")
pheatmap(cor(superior_cor, use = "complete.obs"), display_numbers = TRUE)
michigan_cor <- cbind(matrixToRow(michigan_basin_min_air_temperature), matrixToRow(michigan_basin_max_air_temperature), matrixToRow(michigan_basin_mean_precipitation), matrixToRow(michigan_basin_mean_air_temperature), matrixToRow(michigan_basin_mean_dewpoint), matrixToRow(michigan_basin_mean_wind_speed), matrixToRow(michigan_basin_mean_cloud_cover), matrixToRow(michigan_mean_surface_water_temperature), matrixToRow(michigan_mean_evaporation), matrixToRow(michigan_mean_run_off), matrixToRow(michigan_huron_mean_water_level))
colnames(michigan_cor) <- c("低温", "高温", "降水", "均温", "露点", "风速", "云盖", "水温", "蒸发", "径流", "水位")
pheatmap(cor(michigan_cor, use = "complete.obs"), display_numbers = TRUE)
huron_cor <- cbind(matrixToRow(huron_basin_min_air_temperature), matrixToRow(huron_basin_max_air_temperature), matrixToRow(huron_basin_mean_precipitation), matrixToRow(huron_basin_mean_air_temperature), matrixToRow(huron_basin_mean_dewpoint), matrixToRow(huron_basin_mean_wind_speed), matrixToRow(huron_basin_mean_cloud_cover), matrixToRow(huron_mean_surface_water_temperature), matrixToRow(huron_mean_evaporation), matrixToRow(huron_mean_run_off), matrixToRow(michigan_huron_mean_water_level))
colnames(huron_cor) <- c("低温", "高温", "降水", "均温", "露点", "风速", "云盖", "水温", "蒸发", "径流", "水位")
pheatmap(cor(huron_cor, use = "complete.obs"), display_numbers = TRUE)
erie_cor <- cbind(matrixToRow(erie_basin_min_air_temperature), matrixToRow(erie_basin_max_air_temperature), matrixToRow(erie_basin_mean_precipitation), matrixToRow(erie_basin_mean_air_temperature), matrixToRow(erie_basin_mean_dewpoint), matrixToRow(erie_basin_mean_wind_speed), matrixToRow(erie_basin_mean_cloud_cover), matrixToRow(erie_mean_surface_water_temperature), matrixToRow(erie_mean_evaporation), matrixToRow(erie_mean_run_off), matrixToRow(erie_mean_water_level))
colnames(erie_cor) <- c("低温", "高温", "降水", "均温", "露点", "风速", "云盖", "水温", "蒸发", "径流", "水位")
pheatmap(cor(erie_cor, use = "complete.obs"), display_numbers = TRUE)
ontario_cor <- cbind(matrixToRow(ontario_basin_min_air_temperature), matrixToRow(ontario_basin_max_air_temperature), matrixToRow(ontario_basin_mean_precipitation), matrixToRow(ontario_basin_mean_air_temperature), matrixToRow(ontario_basin_mean_dewpoint), matrixToRow(ontario_basin_mean_wind_speed), matrixToRow(ontario_basin_mean_cloud_cover), matrixToRow(ontario_mean_surface_water_temperature), matrixToRow(ontario_mean_evaporation), matrixToRow(ontario_mean_run_off), matrixToRow(ontario_mean_water_level))
colnames(ontario_cor) <- c("低温", "高温", "降水", "均温", "露点", "风速", "云盖", "水温", "蒸发", "径流", "水位")
pheatmap(cor(ontario_cor, use = "complete.obs"), display_numbers = TRUE)
write.csv(cor(superior_cor, use = "complete.obs"), "第二问/superior.csv")
write.csv(cor(michigan_cor, use = "complete.obs"), "第二问/michigan.csv")
write.csv(cor(huron_cor, use = "complete.obs"), "第二问/huron.csv")
write.csv(cor(erie_cor, use = "complete.obs"), "第二问/erie.csv")
write.csv(cor(ontario_cor, use = "complete.obs"), "第二问/ontario.csv")